### ISSUE TITLE
Scaffold a demo app which integrates with the Holo-REA backend

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-ui#3]
Once we have a component to test (see #2), we should integrate it with a real backend. At this stage my gut feeling is that it makes sense to develop the actual *app* within the Holo-REA codebase, in the `examples` folder.

- [ ] set up [Sapper](https://sapper.svelte.dev/docs) to serve the site
- [ ] bring in `vf-graphql-holochain` and `svelte-apollo` to get GraphQL integrated (the former module should be set up through the project's Yarn workspace, not loaded via NPM)

**Comment by pospi** [comment]
Note that those developing all of these projects simultaneously might want to check out https://github.com/holo-rea/valueflows-project-metarepo/

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/3.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
