### ISSUE TITLE
Implement UI language translations

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-ui#4]
https://github.com/kaisermann/svelte-i18n looks really nice- it provides a simple API for observing changes to the browser locale, but also for asynchronously loading locale files into the browser in response to such changes.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/4.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
