### ISSUE TITLE
App: task management board

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-ui#6]
Likely first candidate for #3.

Basically just means taking #2 and wiring it up to the Holochain backend data source. Work to be committed in https://github.com/holo-rea/holo-rea/.

**Comment by bhaugen** [comment]
Sorry to be so late to respond to this issue. But what does "task" mean in this context?

Does it mean some specific work for a single person to do, like wash the floor?

Does it mean a process which is intended to create some output, like bake a cake? Which process might have some inputs, which might be ingredients, equipment use, and more than one work requirement?

Or somewhere between, like a bug fix which will require a coder and a tester?

Or any and all of the above?

**Comment by pospi** [comment]
Any and all of the above, I think. I haven't explored too far (gotten held up with other work) but it basically depends on what @ivanminutillo's early prototype had in it- I'll just use that to start with and follow on from there.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/6.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
