### ISSUE TITLE
App: promise manager

### ISSUE THREAD

**Issue by pospi** [valueflows/vf-ui#8]
Enable something like https://en.wikipedia.org/wiki/Promise_theory by creating a nice app to manage commitments in economic networks.

**Comment by bhaugen** [comment]
What is the essential difference between promises and intents (offers)?

See also https://en.wikipedia.org/wiki/Promise_theory#Multi-agent_systems_and_commitments
> The theory of commitments in multi-agent systems has some similarities with aspects of promise theory, but there are key differences. In Promise Theory a commitment is a subset of intentions. Since a promise is a published intention, a commitment may or may not be a promise. A detailed comparison of Promises and Commitments in the senses intended in their respective fields is forthcoming, and not a trivial matter.

One difference between promises (as unilateral offers) and commitments is that commitments involve more than one agent agreeing on something. 

For example, if I request somebody to do some work (an intent) and you agree to do it, you have a commitment where you are the provider and I am the planned receiver.

I don't know if economic commitments make sense unilaterally. I may commit to follow my new year's resolutions but it's not quite the same thing.

But for economic networks, commitments between agents is pretty central, and will often follow the matching of offers and requests, which is where the graphs in that promises network would start to emerge. Like in http://locecon.org/ we differentiate potential resource flows (where one agent or function produces some resource that some other agents or functions consume) from actual flows, where agents have transferred resources from one to another. Matched offers and requests would be potential flows, while commitments would be one step closer to actual flows.

Hope that all made sense.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/8.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
