### ISSUE TITLE
No-code and low-code development

### ISSUE THREAD

**Issue by bhaugen** [valueflows/vf-ui#9]
We should be able to do this very well, given vf-graphql, a suite of UI components, and a component that does not exist yet, the component wiring breadboard...
* https://openui5.org/
* https://redmonk.com/jgovernor/2020/02/21/new-client-profile-neptune-software/
    *(founded by another of my mythical cousins...)
* https://www.bettyblocks.com/
* https://www.outsystems.com/
* https://www.mendix.com/

and wiring:
* https://glitch.com/

**Comment by bhaugen** [comment]
I think the recent work that @dahacouk and @oceatoon have been doing might fit in this category.

**Comment by almereyda** [comment]
We have moved the ValueFlows organization from GitHub to https://lab.allmende.io/valueflows.

This issue has been closed here, and all further discussion on this issue can be done at

> https://lab.allmende.io/valueflows/vf-ui/-/issues/9.

If you have not done so, you are very welcome to register at https://lab.allmende.io and join the ValueFlows organization there.
